### ISSUE TITLE
I get an error If there are no elements

### ISSUE THREAD

**Issue by marcomd** [filamentgroup/jQuery-UI-Date-Range-Picker#13]
I get the error if there is no any element. In my case any class rangedcalendar :
$('.rangedcalendar').daterangepicker();

I solved with this update
//daterangepicker.jQuery.js row 108

	if(rangeInput.size() == 2){
		inputDateAtemp = Date.parse( rangeInput.eq(0).val() );
		inputDateBtemp = Date.parse( rangeInput.eq(1).val() );
		if(inputDateAtemp == null){inputDateAtemp = inputDateBtemp;} 
		if(inputDateBtemp == null){inputDateBtemp = inputDateAtemp;}
    } else if(rangeInput.size() == 0) {
        //marcomd
        return null;
	} else {
		inputDateAtemp = Date.parse( rangeInput.val().split(options.rangeSplitter)[0] );
		inputDateBtemp = Date.parse( rangeInput.val().split(options.rangeSplitter)[1] );
		if(inputDateBtemp == null){inputDateBtemp = inputDateAtemp;} //if one date, set both
	}

**Comment by jefflembeck** [comment]
Retiring this project.

Thank you
