### ISSUE TITLE
dateFormat option ignored on input value

### ISSUE THREAD

**Issue by dimitriho** [filamentgroup/jQuery-UI-Date-Range-Picker#14]
The DateRangePicker does not parse the input value using the dateFormat option. Instead, it parse it in english format (mm/dd/yy).

Given this input,

    <input type="text" value="09/01/2012" />

and this javascript code,

```javascript
$(function(){
    $('input').daterangepicker({
        dateFormat: 'dd/mm/yy',
        arrows: true,
        datepickerOptions: {
            dateFormat: 'dd/mm/yy'
        }
    });
});
```

when I click on the right arrow, the input value become "02/09/2012" instead of "10/01/2012" (January, 10th in the dateFormat "dd/mm/yy").

The "Specific date" also opens the calendar on September.

**Comment by jefflembeck** [comment]
Retiring this project.

Thank you
