### ISSUE TITLE
posX and posY don't do anything

### ISSUE THREAD

**Issue by DanielViglione** [filamentgroup/jQuery-UI-Date-Range-Picker#18]
Hey all,

I have the daterangepicker on a toolbar at the bottom of the page. Problem is when I click in the input field, the dropdown drops downward and clips off the page and therefore content does not become selectable. So I thought posX and posY would allow me to rearrange the dropdown to display above the input field. Unfortunately thats not what happened. Any way to move the dropdown so it doesnt drop below the input field but rather renders above it so it doesnt get clipped off page?

thanks for response

**Comment by jefflembeck** [comment]
Retiring this project.

Thank you
