### ISSUE TITLE
Doesn't seem to fire change events on fields. Doesn't interact well with Angular.js

### ISSUE THREAD

**Issue by graingert** [filamentgroup/jQuery-UI-Date-Range-Picker#25]
I have some fields that when they change update part of the angular $scope

I expect that whenever a user selects a date range that the ng:change event would be fired - this is not the case.

A demo of what's happening:

http://jsfiddle.net/we7b9/3/

**Comment by jefflembeck** [comment]
Retiring this project.

Thank you

**Comment by graingert** [comment]
No wories, thanks!
