### ISSUE TITLE
Uncaught Type Error & other observations

### ISSUE THREAD

**Issue by cacycleworks** [filamentgroup/jQuery-UI-Date-Range-Picker#33]
Hi, LOVE your Date range picker!!! 

I noticed a non-critical bug: Uncaught TypeError from line 437. I say non-critical as the plug-in still works. I'm on jquery.min 1.82.  I put that if and its else inside of

    if(  typeof offset !== 'undefined' ) {
        if ( offset.left < 460) //left to right
        ...
    }

![datepicker_error](https://cloud.githubusercontent.com/assets/1783436/3167719/ec3c91e8-eb72-11e3-8051-00b6cdc2ac7c.png)

Other observation:
» It seems #date-range0 must start with 0 and must be numeric. This is what led me to look at the console and resulted in multiple Uncaught TypeErrors and non-functionality of the plug-in.

**Comment by jefflembeck** [comment]
Retiring this project.

Thank you
